package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for FFT_Step_MEM_Real kernel
var FFT_Step_MEM_Real_code cu.Function

// Stores the arguments for FFT_Step_MEM_Real kernel invocation
type FFT_Step_MEM_Real_args_t struct {
	arg_dst  unsafe.Pointer
	arg_src1 unsafe.Pointer
	arg_src2 unsafe.Pointer
	arg_Nx   int
	arg_Ny   int
	arg_Nz   int
	arg_Nf   int
	arg_minF float32
	arg_dF   float32
	arg_t    float32
	arg_n    float32
	argptr   [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for FFT_Step_MEM_Real kernel invocation
var FFT_Step_MEM_Real_args FFT_Step_MEM_Real_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	FFT_Step_MEM_Real_args.argptr[0] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_dst)
	FFT_Step_MEM_Real_args.argptr[1] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_src1)
	FFT_Step_MEM_Real_args.argptr[2] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_src2)
	FFT_Step_MEM_Real_args.argptr[3] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_Nx)
	FFT_Step_MEM_Real_args.argptr[4] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_Ny)
	FFT_Step_MEM_Real_args.argptr[5] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_Nz)
	FFT_Step_MEM_Real_args.argptr[6] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_Nf)
	FFT_Step_MEM_Real_args.argptr[7] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_minF)
	FFT_Step_MEM_Real_args.argptr[8] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_dF)
	FFT_Step_MEM_Real_args.argptr[9] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_t)
	FFT_Step_MEM_Real_args.argptr[10] = unsafe.Pointer(&FFT_Step_MEM_Real_args.arg_n)
}

// Wrapper for FFT_Step_MEM_Real CUDA kernel, asynchronous.
func k_FFT_Step_MEM_Real_async(dst unsafe.Pointer, src1 unsafe.Pointer, src2 unsafe.Pointer, Nx int, Ny int, Nz int, Nf int, minF float32, dF float32, t float32, n float32, key string, cfg *config) {
	if Synchronous { // debug
		SyncFFT_T(key)
		timer.Start("FFT_Step_MEM_Real" + key)
	}

	FFT_Step_MEM_Real_args.Lock()
	defer FFT_Step_MEM_Real_args.Unlock()

	if FFT_Step_MEM_Real_code == 0 {
		FFT_Step_MEM_Real_code = fatbinLoad(FFT_Step_MEM_Real_map, "FFT_Step_MEM_Real")
	}

	FFT_Step_MEM_Real_args.arg_dst = dst
	FFT_Step_MEM_Real_args.arg_src1 = src1
	FFT_Step_MEM_Real_args.arg_src2 = src2
	FFT_Step_MEM_Real_args.arg_Nx = Nx
	FFT_Step_MEM_Real_args.arg_Ny = Ny
	FFT_Step_MEM_Real_args.arg_Nz = Nz
	FFT_Step_MEM_Real_args.arg_Nf = Nf
	FFT_Step_MEM_Real_args.arg_minF = minF
	FFT_Step_MEM_Real_args.arg_dF = dF
	FFT_Step_MEM_Real_args.arg_t = t
	FFT_Step_MEM_Real_args.arg_n = n

	args := FFT_Step_MEM_Real_args.argptr[:]
	cu.LaunchKernel(FFT_Step_MEM_Real_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, Get_Stream(key), args)

	if Synchronous { // debug
		SyncFFT_T(key)
		timer.Stop("FFT_Step_MEM_Real" + key)
	}
}

// maps compute capability on PTX code for FFT_Step_MEM_Real kernel.
var FFT_Step_MEM_Real_map = map[int]string{0: "",
	50: FFT_Step_MEM_Real_ptx_50,
	52: FFT_Step_MEM_Real_ptx_52,
	53: FFT_Step_MEM_Real_ptx_53,
	60: FFT_Step_MEM_Real_ptx_60,
	61: FFT_Step_MEM_Real_ptx_61,
	62: FFT_Step_MEM_Real_ptx_62,
	70: FFT_Step_MEM_Real_ptx_70,
	72: FFT_Step_MEM_Real_ptx_72,
	75: FFT_Step_MEM_Real_ptx_75,
	80: FFT_Step_MEM_Real_ptx_80}

// FFT_Step_MEM_Real PTX code for various compute capabilities.
const (
	FFT_Step_MEM_Real_ptx_50 = `
.version 8.5
.target sm_50
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<94>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r89, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r89;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r93, %f31;
	cvt.rn.f32.s32 	%f32, %r93;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r93, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	bfe.u32 	%r54, %r9, 23, 8;
	add.s32 	%r10, %r54, -128;
	shl.b32 	%r55, %r9, 8;
	or.b32  	%r11, %r55, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r90, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r56, [%rd31];
	mad.wide.u32 	%rd19, %r56, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r90, %r90, 1;
	setp.ne.s32 	%p5, %r90, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r57, 4;
	sub.s32 	%r15, %r57, %r12;
	mov.u32 	%r58, 6;
	sub.s32 	%r59, %r58, %r12;
	mul.wide.s32 	%rd20, %r59, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r91, [%rd21];
	ld.local.u32 	%r92, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r60, 32;
	sub.s32 	%r61, %r60, %r18;
	shr.u32 	%r62, %r92, %r61;
	shl.b32 	%r63, %r91, %r18;
	add.s32 	%r91, %r62, %r63;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r64, [%rd23];
	shr.u32 	%r65, %r64, %r61;
	shl.b32 	%r66, %r92, %r18;
	add.s32 	%r92, %r65, %r66;

$L__BB0_9:
	and.b32  	%r67, %r9, -2147483648;
	shr.u32 	%r68, %r92, 30;
	shl.b32 	%r69, %r91, 2;
	or.b32  	%r70, %r68, %r69;
	shr.u32 	%r71, %r70, 31;
	shr.u32 	%r72, %r91, 30;
	add.s32 	%r73, %r71, %r72;
	neg.s32 	%r74, %r73;
	setp.eq.s32 	%p7, %r67, 0;
	selp.b32 	%r93, %r73, %r74, %p7;
	setp.ne.s32 	%p8, %r71, 0;
	xor.b32  	%r75, %r67, -2147483648;
	selp.b32 	%r76, %r75, %r67, %p8;
	selp.b32 	%r77, -1, 0, %p8;
	xor.b32  	%r78, %r70, %r77;
	shl.b32 	%r79, %r92, 2;
	xor.b32  	%r80, %r79, %r77;
	cvt.u64.u32 	%rd24, %r78;
	cvt.u64.u32 	%rd25, %r80;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r76, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r82, %r93, 1;
	setp.eq.b32 	%p10, %r82, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r83, %r93, 2;
	setp.eq.s32 	%p11, %r83, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r84, %r93, 1;
	and.b32  	%r85, %r84, 2;
	setp.eq.s32 	%p12, %r85, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r86, %r89, %r28, %r5;
	mad.lo.s32 	%r87, %r86, %r27, %r4;
	mad.lo.s32 	%r88, %r87, %r26, %r6;
	mul.wide.s32 	%rd27, %r88, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r89, %r89, 1;
	setp.lt.s32 	%p13, %r89, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_52 = `
.version 8.5
.target sm_52
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<94>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r89, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r89;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r93, %f31;
	cvt.rn.f32.s32 	%f32, %r93;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r93, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	bfe.u32 	%r54, %r9, 23, 8;
	add.s32 	%r10, %r54, -128;
	shl.b32 	%r55, %r9, 8;
	or.b32  	%r11, %r55, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r90, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r56, [%rd31];
	mad.wide.u32 	%rd19, %r56, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r90, %r90, 1;
	setp.ne.s32 	%p5, %r90, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r57, 4;
	sub.s32 	%r15, %r57, %r12;
	mov.u32 	%r58, 6;
	sub.s32 	%r59, %r58, %r12;
	mul.wide.s32 	%rd20, %r59, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r91, [%rd21];
	ld.local.u32 	%r92, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r60, 32;
	sub.s32 	%r61, %r60, %r18;
	shr.u32 	%r62, %r92, %r61;
	shl.b32 	%r63, %r91, %r18;
	add.s32 	%r91, %r62, %r63;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r64, [%rd23];
	shr.u32 	%r65, %r64, %r61;
	shl.b32 	%r66, %r92, %r18;
	add.s32 	%r92, %r65, %r66;

$L__BB0_9:
	and.b32  	%r67, %r9, -2147483648;
	shr.u32 	%r68, %r92, 30;
	shl.b32 	%r69, %r91, 2;
	or.b32  	%r70, %r68, %r69;
	shr.u32 	%r71, %r70, 31;
	shr.u32 	%r72, %r91, 30;
	add.s32 	%r73, %r71, %r72;
	neg.s32 	%r74, %r73;
	setp.eq.s32 	%p7, %r67, 0;
	selp.b32 	%r93, %r73, %r74, %p7;
	setp.ne.s32 	%p8, %r71, 0;
	xor.b32  	%r75, %r67, -2147483648;
	selp.b32 	%r76, %r75, %r67, %p8;
	selp.b32 	%r77, -1, 0, %p8;
	xor.b32  	%r78, %r70, %r77;
	shl.b32 	%r79, %r92, 2;
	xor.b32  	%r80, %r79, %r77;
	cvt.u64.u32 	%rd24, %r78;
	cvt.u64.u32 	%rd25, %r80;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r76, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r82, %r93, 1;
	setp.eq.b32 	%p10, %r82, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r83, %r93, 2;
	setp.eq.s32 	%p11, %r83, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r84, %r93, 1;
	and.b32  	%r85, %r84, 2;
	setp.eq.s32 	%p12, %r85, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r86, %r89, %r28, %r5;
	mad.lo.s32 	%r87, %r86, %r27, %r4;
	mad.lo.s32 	%r88, %r87, %r26, %r6;
	mul.wide.s32 	%rd27, %r88, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r89, %r89, 1;
	setp.lt.s32 	%p13, %r89, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_53 = `
.version 8.5
.target sm_53
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<94>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r89, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r89;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r93, %f31;
	cvt.rn.f32.s32 	%f32, %r93;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r93, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	bfe.u32 	%r54, %r9, 23, 8;
	add.s32 	%r10, %r54, -128;
	shl.b32 	%r55, %r9, 8;
	or.b32  	%r11, %r55, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r90, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r56, [%rd31];
	mad.wide.u32 	%rd19, %r56, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r90, %r90, 1;
	setp.ne.s32 	%p5, %r90, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r57, 4;
	sub.s32 	%r15, %r57, %r12;
	mov.u32 	%r58, 6;
	sub.s32 	%r59, %r58, %r12;
	mul.wide.s32 	%rd20, %r59, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r91, [%rd21];
	ld.local.u32 	%r92, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r60, 32;
	sub.s32 	%r61, %r60, %r18;
	shr.u32 	%r62, %r92, %r61;
	shl.b32 	%r63, %r91, %r18;
	add.s32 	%r91, %r62, %r63;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r64, [%rd23];
	shr.u32 	%r65, %r64, %r61;
	shl.b32 	%r66, %r92, %r18;
	add.s32 	%r92, %r65, %r66;

$L__BB0_9:
	and.b32  	%r67, %r9, -2147483648;
	shr.u32 	%r68, %r92, 30;
	shl.b32 	%r69, %r91, 2;
	or.b32  	%r70, %r68, %r69;
	shr.u32 	%r71, %r70, 31;
	shr.u32 	%r72, %r91, 30;
	add.s32 	%r73, %r71, %r72;
	neg.s32 	%r74, %r73;
	setp.eq.s32 	%p7, %r67, 0;
	selp.b32 	%r93, %r73, %r74, %p7;
	setp.ne.s32 	%p8, %r71, 0;
	xor.b32  	%r75, %r67, -2147483648;
	selp.b32 	%r76, %r75, %r67, %p8;
	selp.b32 	%r77, -1, 0, %p8;
	xor.b32  	%r78, %r70, %r77;
	shl.b32 	%r79, %r92, 2;
	xor.b32  	%r80, %r79, %r77;
	cvt.u64.u32 	%rd24, %r78;
	cvt.u64.u32 	%rd25, %r80;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r76, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r82, %r93, 1;
	setp.eq.b32 	%p10, %r82, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r83, %r93, 2;
	setp.eq.s32 	%p11, %r83, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r84, %r93, 1;
	and.b32  	%r85, %r84, 2;
	setp.eq.s32 	%p12, %r85, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r86, %r89, %r28, %r5;
	mad.lo.s32 	%r87, %r86, %r27, %r4;
	mad.lo.s32 	%r88, %r87, %r26, %r6;
	mul.wide.s32 	%rd27, %r88, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r89, %r89, 1;
	setp.lt.s32 	%p13, %r89, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_60 = `
.version 8.5
.target sm_60
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<94>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r89, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r89;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r93, %f31;
	cvt.rn.f32.s32 	%f32, %r93;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r93, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	bfe.u32 	%r54, %r9, 23, 8;
	add.s32 	%r10, %r54, -128;
	shl.b32 	%r55, %r9, 8;
	or.b32  	%r11, %r55, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r90, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r56, [%rd31];
	mad.wide.u32 	%rd19, %r56, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r90, %r90, 1;
	setp.ne.s32 	%p5, %r90, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r57, 4;
	sub.s32 	%r15, %r57, %r12;
	mov.u32 	%r58, 6;
	sub.s32 	%r59, %r58, %r12;
	mul.wide.s32 	%rd20, %r59, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r91, [%rd21];
	ld.local.u32 	%r92, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r60, 32;
	sub.s32 	%r61, %r60, %r18;
	shr.u32 	%r62, %r92, %r61;
	shl.b32 	%r63, %r91, %r18;
	add.s32 	%r91, %r62, %r63;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r64, [%rd23];
	shr.u32 	%r65, %r64, %r61;
	shl.b32 	%r66, %r92, %r18;
	add.s32 	%r92, %r65, %r66;

$L__BB0_9:
	and.b32  	%r67, %r9, -2147483648;
	shr.u32 	%r68, %r92, 30;
	shl.b32 	%r69, %r91, 2;
	or.b32  	%r70, %r68, %r69;
	shr.u32 	%r71, %r70, 31;
	shr.u32 	%r72, %r91, 30;
	add.s32 	%r73, %r71, %r72;
	neg.s32 	%r74, %r73;
	setp.eq.s32 	%p7, %r67, 0;
	selp.b32 	%r93, %r73, %r74, %p7;
	setp.ne.s32 	%p8, %r71, 0;
	xor.b32  	%r75, %r67, -2147483648;
	selp.b32 	%r76, %r75, %r67, %p8;
	selp.b32 	%r77, -1, 0, %p8;
	xor.b32  	%r78, %r70, %r77;
	shl.b32 	%r79, %r92, 2;
	xor.b32  	%r80, %r79, %r77;
	cvt.u64.u32 	%rd24, %r78;
	cvt.u64.u32 	%rd25, %r80;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r76, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r82, %r93, 1;
	setp.eq.b32 	%p10, %r82, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r83, %r93, 2;
	setp.eq.s32 	%p11, %r83, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r84, %r93, 1;
	and.b32  	%r85, %r84, 2;
	setp.eq.s32 	%p12, %r85, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r86, %r89, %r28, %r5;
	mad.lo.s32 	%r87, %r86, %r27, %r4;
	mad.lo.s32 	%r88, %r87, %r26, %r6;
	mul.wide.s32 	%rd27, %r88, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r89, %r89, 1;
	setp.lt.s32 	%p13, %r89, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<94>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r89, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r89;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r93, %f31;
	cvt.rn.f32.s32 	%f32, %r93;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r93, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	bfe.u32 	%r54, %r9, 23, 8;
	add.s32 	%r10, %r54, -128;
	shl.b32 	%r55, %r9, 8;
	or.b32  	%r11, %r55, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r90, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r56, [%rd31];
	mad.wide.u32 	%rd19, %r56, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r90, %r90, 1;
	setp.ne.s32 	%p5, %r90, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r57, 4;
	sub.s32 	%r15, %r57, %r12;
	mov.u32 	%r58, 6;
	sub.s32 	%r59, %r58, %r12;
	mul.wide.s32 	%rd20, %r59, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r91, [%rd21];
	ld.local.u32 	%r92, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r60, 32;
	sub.s32 	%r61, %r60, %r18;
	shr.u32 	%r62, %r92, %r61;
	shl.b32 	%r63, %r91, %r18;
	add.s32 	%r91, %r62, %r63;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r64, [%rd23];
	shr.u32 	%r65, %r64, %r61;
	shl.b32 	%r66, %r92, %r18;
	add.s32 	%r92, %r65, %r66;

$L__BB0_9:
	and.b32  	%r67, %r9, -2147483648;
	shr.u32 	%r68, %r92, 30;
	shl.b32 	%r69, %r91, 2;
	or.b32  	%r70, %r68, %r69;
	shr.u32 	%r71, %r70, 31;
	shr.u32 	%r72, %r91, 30;
	add.s32 	%r73, %r71, %r72;
	neg.s32 	%r74, %r73;
	setp.eq.s32 	%p7, %r67, 0;
	selp.b32 	%r93, %r73, %r74, %p7;
	setp.ne.s32 	%p8, %r71, 0;
	xor.b32  	%r75, %r67, -2147483648;
	selp.b32 	%r76, %r75, %r67, %p8;
	selp.b32 	%r77, -1, 0, %p8;
	xor.b32  	%r78, %r70, %r77;
	shl.b32 	%r79, %r92, 2;
	xor.b32  	%r80, %r79, %r77;
	cvt.u64.u32 	%rd24, %r78;
	cvt.u64.u32 	%rd25, %r80;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r76, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r82, %r93, 1;
	setp.eq.b32 	%p10, %r82, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r83, %r93, 2;
	setp.eq.s32 	%p11, %r83, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r84, %r93, 1;
	and.b32  	%r85, %r84, 2;
	setp.eq.s32 	%p12, %r85, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r86, %r89, %r28, %r5;
	mad.lo.s32 	%r87, %r86, %r27, %r4;
	mad.lo.s32 	%r88, %r87, %r26, %r6;
	mul.wide.s32 	%rd27, %r88, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r89, %r89, 1;
	setp.lt.s32 	%p13, %r89, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_62 = `
.version 8.5
.target sm_62
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<94>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r89, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r89;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r93, %f31;
	cvt.rn.f32.s32 	%f32, %r93;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r93, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	bfe.u32 	%r54, %r9, 23, 8;
	add.s32 	%r10, %r54, -128;
	shl.b32 	%r55, %r9, 8;
	or.b32  	%r11, %r55, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r90, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r56, [%rd31];
	mad.wide.u32 	%rd19, %r56, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r90, %r90, 1;
	setp.ne.s32 	%p5, %r90, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r57, 4;
	sub.s32 	%r15, %r57, %r12;
	mov.u32 	%r58, 6;
	sub.s32 	%r59, %r58, %r12;
	mul.wide.s32 	%rd20, %r59, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r91, [%rd21];
	ld.local.u32 	%r92, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r60, 32;
	sub.s32 	%r61, %r60, %r18;
	shr.u32 	%r62, %r92, %r61;
	shl.b32 	%r63, %r91, %r18;
	add.s32 	%r91, %r62, %r63;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r64, [%rd23];
	shr.u32 	%r65, %r64, %r61;
	shl.b32 	%r66, %r92, %r18;
	add.s32 	%r92, %r65, %r66;

$L__BB0_9:
	and.b32  	%r67, %r9, -2147483648;
	shr.u32 	%r68, %r92, 30;
	shl.b32 	%r69, %r91, 2;
	or.b32  	%r70, %r68, %r69;
	shr.u32 	%r71, %r70, 31;
	shr.u32 	%r72, %r91, 30;
	add.s32 	%r73, %r71, %r72;
	neg.s32 	%r74, %r73;
	setp.eq.s32 	%p7, %r67, 0;
	selp.b32 	%r93, %r73, %r74, %p7;
	setp.ne.s32 	%p8, %r71, 0;
	xor.b32  	%r75, %r67, -2147483648;
	selp.b32 	%r76, %r75, %r67, %p8;
	selp.b32 	%r77, -1, 0, %p8;
	xor.b32  	%r78, %r70, %r77;
	shl.b32 	%r79, %r92, 2;
	xor.b32  	%r80, %r79, %r77;
	cvt.u64.u32 	%rd24, %r78;
	cvt.u64.u32 	%rd25, %r80;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r76, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r82, %r93, 1;
	setp.eq.b32 	%p10, %r82, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r83, %r93, 2;
	setp.eq.s32 	%p11, %r83, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r84, %r93, 1;
	and.b32  	%r85, %r84, 2;
	setp.eq.s32 	%p12, %r85, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r86, %r89, %r28, %r5;
	mad.lo.s32 	%r87, %r86, %r27, %r4;
	mad.lo.s32 	%r88, %r87, %r26, %r6;
	mul.wide.s32 	%rd27, %r88, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r89, %r89, 1;
	setp.lt.s32 	%p13, %r89, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_70 = `
.version 8.5
.target sm_70
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<95>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r90, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r90;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r94, %f31;
	cvt.rn.f32.s32 	%f32, %r94;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r94, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	shr.u32 	%r54, %r9, 23;
	and.b32  	%r55, %r54, 255;
	add.s32 	%r10, %r55, -128;
	shl.b32 	%r56, %r9, 8;
	or.b32  	%r11, %r56, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r91, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r57, [%rd31];
	mad.wide.u32 	%rd19, %r57, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r91, %r91, 1;
	setp.ne.s32 	%p5, %r91, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r58, 4;
	sub.s32 	%r15, %r58, %r12;
	mov.u32 	%r59, 6;
	sub.s32 	%r60, %r59, %r12;
	mul.wide.s32 	%rd20, %r60, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r92, [%rd21];
	ld.local.u32 	%r93, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r61, 32;
	sub.s32 	%r62, %r61, %r18;
	shr.u32 	%r63, %r93, %r62;
	shl.b32 	%r64, %r92, %r18;
	add.s32 	%r92, %r63, %r64;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r65, [%rd23];
	shr.u32 	%r66, %r65, %r62;
	shl.b32 	%r67, %r93, %r18;
	add.s32 	%r93, %r66, %r67;

$L__BB0_9:
	and.b32  	%r68, %r9, -2147483648;
	shr.u32 	%r69, %r93, 30;
	shl.b32 	%r70, %r92, 2;
	or.b32  	%r71, %r69, %r70;
	shr.u32 	%r72, %r71, 31;
	shr.u32 	%r73, %r92, 30;
	add.s32 	%r74, %r72, %r73;
	neg.s32 	%r75, %r74;
	setp.eq.s32 	%p7, %r68, 0;
	selp.b32 	%r94, %r74, %r75, %p7;
	setp.ne.s32 	%p8, %r72, 0;
	xor.b32  	%r76, %r68, -2147483648;
	selp.b32 	%r77, %r76, %r68, %p8;
	selp.b32 	%r78, -1, 0, %p8;
	xor.b32  	%r79, %r71, %r78;
	shl.b32 	%r80, %r93, 2;
	xor.b32  	%r81, %r80, %r78;
	cvt.u64.u32 	%rd24, %r79;
	cvt.u64.u32 	%rd25, %r81;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r77, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r83, %r94, 1;
	setp.eq.b32 	%p10, %r83, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r84, %r94, 2;
	setp.eq.s32 	%p11, %r84, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r85, %r94, 1;
	and.b32  	%r86, %r85, 2;
	setp.eq.s32 	%p12, %r86, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r87, %r90, %r28, %r5;
	mad.lo.s32 	%r88, %r87, %r27, %r4;
	mad.lo.s32 	%r89, %r88, %r26, %r6;
	mul.wide.s32 	%rd27, %r89, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r90, %r90, 1;
	setp.lt.s32 	%p13, %r90, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_72 = `
.version 8.5
.target sm_72
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<95>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r90, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r90;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r94, %f31;
	cvt.rn.f32.s32 	%f32, %r94;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r94, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	shr.u32 	%r54, %r9, 23;
	and.b32  	%r55, %r54, 255;
	add.s32 	%r10, %r55, -128;
	shl.b32 	%r56, %r9, 8;
	or.b32  	%r11, %r56, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r91, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r57, [%rd31];
	mad.wide.u32 	%rd19, %r57, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r91, %r91, 1;
	setp.ne.s32 	%p5, %r91, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r58, 4;
	sub.s32 	%r15, %r58, %r12;
	mov.u32 	%r59, 6;
	sub.s32 	%r60, %r59, %r12;
	mul.wide.s32 	%rd20, %r60, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r92, [%rd21];
	ld.local.u32 	%r93, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r61, 32;
	sub.s32 	%r62, %r61, %r18;
	shr.u32 	%r63, %r93, %r62;
	shl.b32 	%r64, %r92, %r18;
	add.s32 	%r92, %r63, %r64;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r65, [%rd23];
	shr.u32 	%r66, %r65, %r62;
	shl.b32 	%r67, %r93, %r18;
	add.s32 	%r93, %r66, %r67;

$L__BB0_9:
	and.b32  	%r68, %r9, -2147483648;
	shr.u32 	%r69, %r93, 30;
	shl.b32 	%r70, %r92, 2;
	or.b32  	%r71, %r69, %r70;
	shr.u32 	%r72, %r71, 31;
	shr.u32 	%r73, %r92, 30;
	add.s32 	%r74, %r72, %r73;
	neg.s32 	%r75, %r74;
	setp.eq.s32 	%p7, %r68, 0;
	selp.b32 	%r94, %r74, %r75, %p7;
	setp.ne.s32 	%p8, %r72, 0;
	xor.b32  	%r76, %r68, -2147483648;
	selp.b32 	%r77, %r76, %r68, %p8;
	selp.b32 	%r78, -1, 0, %p8;
	xor.b32  	%r79, %r71, %r78;
	shl.b32 	%r80, %r93, 2;
	xor.b32  	%r81, %r80, %r78;
	cvt.u64.u32 	%rd24, %r79;
	cvt.u64.u32 	%rd25, %r81;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r77, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r83, %r94, 1;
	setp.eq.b32 	%p10, %r83, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r84, %r94, 2;
	setp.eq.s32 	%p11, %r84, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r85, %r94, 1;
	and.b32  	%r86, %r85, 2;
	setp.eq.s32 	%p12, %r86, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r87, %r90, %r28, %r5;
	mad.lo.s32 	%r88, %r87, %r27, %r4;
	mad.lo.s32 	%r89, %r88, %r26, %r6;
	mul.wide.s32 	%rd27, %r89, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r90, %r90, 1;
	setp.lt.s32 	%p13, %r90, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_75 = `
.version 8.5
.target sm_75
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<95>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r90, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r90;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r94, %f31;
	cvt.rn.f32.s32 	%f32, %r94;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r94, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	shr.u32 	%r54, %r9, 23;
	and.b32  	%r55, %r54, 255;
	add.s32 	%r10, %r55, -128;
	shl.b32 	%r56, %r9, 8;
	or.b32  	%r11, %r56, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r91, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r57, [%rd31];
	mad.wide.u32 	%rd19, %r57, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r91, %r91, 1;
	setp.ne.s32 	%p5, %r91, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r58, 4;
	sub.s32 	%r15, %r58, %r12;
	mov.u32 	%r59, 6;
	sub.s32 	%r60, %r59, %r12;
	mul.wide.s32 	%rd20, %r60, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r92, [%rd21];
	ld.local.u32 	%r93, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r61, 32;
	sub.s32 	%r62, %r61, %r18;
	shr.u32 	%r63, %r93, %r62;
	shl.b32 	%r64, %r92, %r18;
	add.s32 	%r92, %r63, %r64;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r65, [%rd23];
	shr.u32 	%r66, %r65, %r62;
	shl.b32 	%r67, %r93, %r18;
	add.s32 	%r93, %r66, %r67;

$L__BB0_9:
	and.b32  	%r68, %r9, -2147483648;
	shr.u32 	%r69, %r93, 30;
	shl.b32 	%r70, %r92, 2;
	or.b32  	%r71, %r69, %r70;
	shr.u32 	%r72, %r71, 31;
	shr.u32 	%r73, %r92, 30;
	add.s32 	%r74, %r72, %r73;
	neg.s32 	%r75, %r74;
	setp.eq.s32 	%p7, %r68, 0;
	selp.b32 	%r94, %r74, %r75, %p7;
	setp.ne.s32 	%p8, %r72, 0;
	xor.b32  	%r76, %r68, -2147483648;
	selp.b32 	%r77, %r76, %r68, %p8;
	selp.b32 	%r78, -1, 0, %p8;
	xor.b32  	%r79, %r71, %r78;
	shl.b32 	%r80, %r93, 2;
	xor.b32  	%r81, %r80, %r78;
	cvt.u64.u32 	%rd24, %r79;
	cvt.u64.u32 	%rd25, %r81;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r77, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r83, %r94, 1;
	setp.eq.b32 	%p10, %r83, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r84, %r94, 2;
	setp.eq.s32 	%p11, %r84, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r85, %r94, 1;
	and.b32  	%r86, %r85, 2;
	setp.eq.s32 	%p12, %r86, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r87, %r90, %r28, %r5;
	mad.lo.s32 	%r88, %r87, %r27, %r4;
	mad.lo.s32 	%r89, %r88, %r26, %r6;
	mul.wide.s32 	%rd27, %r89, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r90, %r90, 1;
	setp.lt.s32 	%p13, %r90, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
	FFT_Step_MEM_Real_ptx_80 = `
.version 8.5
.target sm_80
.address_size 64

	// .globl	FFT_Step_MEM_Real
.global .align 4 .b8 __cudart_i2opi_f[24] = {65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry FFT_Step_MEM_Real(
	.param .u64 FFT_Step_MEM_Real_param_0,
	.param .u64 FFT_Step_MEM_Real_param_1,
	.param .u64 FFT_Step_MEM_Real_param_2,
	.param .u32 FFT_Step_MEM_Real_param_3,
	.param .u32 FFT_Step_MEM_Real_param_4,
	.param .u32 FFT_Step_MEM_Real_param_5,
	.param .u32 FFT_Step_MEM_Real_param_6,
	.param .f32 FFT_Step_MEM_Real_param_7,
	.param .f32 FFT_Step_MEM_Real_param_8,
	.param .f32 FFT_Step_MEM_Real_param_9,
	.param .f32 FFT_Step_MEM_Real_param_10
)
{
	.local .align 4 .b8 	__local_depot0[28];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<14>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<95>;
	.reg .f64 	%fd<7>;
	.reg .b64 	%rd<33>;


	mov.u64 	%SPL, __local_depot0;
	ld.param.u64 	%rd10, [FFT_Step_MEM_Real_param_0];
	ld.param.u64 	%rd11, [FFT_Step_MEM_Real_param_1];
	ld.param.u64 	%rd12, [FFT_Step_MEM_Real_param_2];
	ld.param.u32 	%r26, [FFT_Step_MEM_Real_param_3];
	ld.param.u32 	%r27, [FFT_Step_MEM_Real_param_4];
	ld.param.u32 	%r28, [FFT_Step_MEM_Real_param_5];
	ld.param.u32 	%r29, [FFT_Step_MEM_Real_param_6];
	ld.param.f32 	%f9, [FFT_Step_MEM_Real_param_7];
	ld.param.f32 	%f10, [FFT_Step_MEM_Real_param_8];
	ld.param.f32 	%f11, [FFT_Step_MEM_Real_param_9];
	ld.param.f32 	%f12, [FFT_Step_MEM_Real_param_10];
	add.u64 	%rd1, %SPL, 0;
	mov.u32 	%r30, %nctaid.x;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %ctaid.x;
	mad.lo.s32 	%r33, %r31, %r30, %r32;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mul.lo.s32 	%r2, %r27, %r26;
	mul.lo.s32 	%r36, %r2, %r28;
	shr.u32 	%r37, %r36, 31;
	add.s32 	%r38, %r36, %r37;
	shr.s32 	%r39, %r38, 1;
	setp.ge.s32 	%p1, %r1, %r39;
	@%p1 bra 	$L__BB0_12;

	div.s32 	%r40, %r1, %r26;
	mul.lo.s32 	%r41, %r40, %r26;
	sub.s32 	%r3, %r1, %r41;
	rem.s32 	%r4, %r40, %r27;
	mul.lo.s32 	%r42, %r4, %r26;
	sub.s32 	%r43, %r41, %r42;
	div.s32 	%r44, %r43, %r2;
	rem.s32 	%r5, %r44, %r28;
	setp.lt.s32 	%p2, %r29, 1;
	@%p2 bra 	$L__BB0_12;

	shl.b32 	%r6, %r3, 1;
	shr.u32 	%r46, %r26, 31;
	add.s32 	%r47, %r26, %r46;
	shr.s32 	%r48, %r47, 1;
	mad.lo.s32 	%r49, %r5, %r27, %r4;
	mad.lo.s32 	%r50, %r49, %r48, %r3;
	cvta.to.global.u64 	%rd14, %rd12;
	mul.wide.s32 	%rd15, %r50, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f1, [%rd16];
	cvt.f64.f32 	%fd1, %f11;
	mov.f32 	%f13, 0f3F000000;
	mov.f32 	%f14, 0f3BBB989D;
	mov.f32 	%f15, 0f00000000;
	fma.rn.f32 	%f16, %f15, %f14, %f13;
	cvt.sat.f32.f32 	%f17, %f16;
	mov.f32 	%f18, 0f4B400001;
	mov.f32 	%f19, 0f437C0000;
	fma.rm.f32 	%f20, %f17, %f19, %f18;
	add.f32 	%f21, %f20, 0fCB40007F;
	neg.f32 	%f22, %f21;
	mov.f32 	%f23, 0f3FB8AA3B;
	fma.rn.f32 	%f24, %f15, %f23, %f22;
	mov.f32 	%f25, 0f32A57060;
	fma.rn.f32 	%f26, %f15, %f25, %f24;
	mov.b32 	%r51, %f20;
	shl.b32 	%r52, %r51, 23;
	mov.b32 	%f27, %r52;
	ex2.approx.ftz.f32 	%f28, %f26;
	mul.f32 	%f2, %f28, %f27;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r90, 0;
	mov.u64 	%rd17, __cudart_i2opi_f;

$L__BB0_3:
	cvt.rn.f32.s32 	%f29, %r90;
	fma.rn.f32 	%f30, %f29, %f10, %f9;
	cvt.f64.f32 	%fd2, %f30;
	mul.f64 	%fd3, %fd2, 0dC01921FB54442D18;
	mul.f64 	%fd4, %fd3, %fd1;
	cvt.rn.f32.f64 	%f3, %fd4;
	mul.f32 	%f31, %f3, 0f3F22F983;
	cvt.rni.s32.f32 	%r94, %f31;
	cvt.rn.f32.s32 	%f32, %r94;
	mov.f32 	%f33, 0fBFC90FDA;
	fma.rn.f32 	%f34, %f32, %f33, %f3;
	mov.f32 	%f35, 0fB3A22168;
	fma.rn.f32 	%f36, %f32, %f35, %f34;
	mov.f32 	%f37, 0fA7C234C5;
	fma.rn.f32 	%f78, %f32, %f37, %f36;
	abs.f32 	%f5, %f3;
	setp.ltu.f32 	%p3, %f5, 0f47CE4780;
	@%p3 bra 	$L__BB0_11;

	setp.eq.f32 	%p4, %f5, 0f7F800000;
	@%p4 bra 	$L__BB0_10;
	bra.uni 	$L__BB0_5;

$L__BB0_10:
	mov.f32 	%f40, 0f00000000;
	mul.rn.f32 	%f78, %f3, %f40;
	mov.u32 	%r94, 0;
	bra.uni 	$L__BB0_11;

$L__BB0_5:
	mov.b32 	%r9, %f3;
	shr.u32 	%r54, %r9, 23;
	and.b32  	%r55, %r54, 255;
	add.s32 	%r10, %r55, -128;
	shl.b32 	%r56, %r9, 8;
	or.b32  	%r11, %r56, -2147483648;
	shr.u32 	%r12, %r10, 5;
	mov.u64 	%rd32, 0;
	mov.u32 	%r91, 0;
	mov.u64 	%rd30, %rd1;
	mov.u64 	%rd31, %rd17;

$L__BB0_6:
	.pragma "nounroll";
	ld.global.nc.u32 	%r57, [%rd31];
	mad.wide.u32 	%rd19, %r57, %r11, %rd32;
	shr.u64 	%rd32, %rd19, 32;
	st.local.u32 	[%rd30], %rd19;
	add.s64 	%rd31, %rd31, 4;
	add.s64 	%rd30, %rd30, 4;
	add.s32 	%r91, %r91, 1;
	setp.ne.s32 	%p5, %r91, 6;
	@%p5 bra 	$L__BB0_6;

	st.local.u32 	[%rd1+24], %rd32;
	mov.u32 	%r58, 4;
	sub.s32 	%r15, %r58, %r12;
	mov.u32 	%r59, 6;
	sub.s32 	%r60, %r59, %r12;
	mul.wide.s32 	%rd20, %r60, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.local.u32 	%r92, [%rd21];
	ld.local.u32 	%r93, [%rd21+-4];
	and.b32  	%r18, %r10, 31;
	setp.eq.s32 	%p6, %r18, 0;
	@%p6 bra 	$L__BB0_9;

	mov.u32 	%r61, 32;
	sub.s32 	%r62, %r61, %r18;
	shr.u32 	%r63, %r93, %r62;
	shl.b32 	%r64, %r92, %r18;
	add.s32 	%r92, %r63, %r64;
	mul.wide.s32 	%rd22, %r15, 4;
	add.s64 	%rd23, %rd1, %rd22;
	ld.local.u32 	%r65, [%rd23];
	shr.u32 	%r66, %r65, %r62;
	shl.b32 	%r67, %r93, %r18;
	add.s32 	%r93, %r66, %r67;

$L__BB0_9:
	and.b32  	%r68, %r9, -2147483648;
	shr.u32 	%r69, %r93, 30;
	shl.b32 	%r70, %r92, 2;
	or.b32  	%r71, %r69, %r70;
	shr.u32 	%r72, %r71, 31;
	shr.u32 	%r73, %r92, 30;
	add.s32 	%r74, %r72, %r73;
	neg.s32 	%r75, %r74;
	setp.eq.s32 	%p7, %r68, 0;
	selp.b32 	%r94, %r74, %r75, %p7;
	setp.ne.s32 	%p8, %r72, 0;
	xor.b32  	%r76, %r68, -2147483648;
	selp.b32 	%r77, %r76, %r68, %p8;
	selp.b32 	%r78, -1, 0, %p8;
	xor.b32  	%r79, %r71, %r78;
	shl.b32 	%r80, %r93, 2;
	xor.b32  	%r81, %r80, %r78;
	cvt.u64.u32 	%rd24, %r79;
	cvt.u64.u32 	%rd25, %r81;
	bfi.b64 	%rd26, %rd24, %rd25, 32, 32;
	cvt.rn.f64.s64 	%fd5, %rd26;
	mul.f64 	%fd6, %fd5, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f38, %fd6;
	setp.eq.s32 	%p9, %r77, 0;
	neg.f32 	%f39, %f38;
	selp.f32 	%f78, %f38, %f39, %p9;

$L__BB0_11:
	mul.f32 	%f41, %f78, %f78;
	mov.f32 	%f42, 0fBAB607ED;
	mov.f32 	%f43, 0f37CBAC00;
	fma.rn.f32 	%f44, %f43, %f41, %f42;
	mov.f32 	%f45, 0f3D2AAABB;
	fma.rn.f32 	%f46, %f44, %f41, %f45;
	mov.f32 	%f47, 0fBEFFFFFF;
	fma.rn.f32 	%f48, %f46, %f41, %f47;
	mov.f32 	%f49, 0f3F800000;
	fma.rn.f32 	%f50, %f48, %f41, %f49;
	mov.f32 	%f51, 0f00000000;
	fma.rn.f32 	%f52, %f41, %f78, %f51;
	mov.f32 	%f53, 0f3C0885E4;
	mov.f32 	%f54, 0fB94D4153;
	fma.rn.f32 	%f55, %f54, %f41, %f53;
	mov.f32 	%f56, 0fBE2AAAA8;
	fma.rn.f32 	%f57, %f55, %f41, %f56;
	fma.rn.f32 	%f58, %f57, %f52, %f78;
	and.b32  	%r83, %r94, 1;
	setp.eq.b32 	%p10, %r83, 1;
	selp.f32 	%f59, %f50, %f58, %p10;
	selp.f32 	%f60, %f58, %f50, %p10;
	and.b32  	%r84, %r94, 2;
	setp.eq.s32 	%p11, %r84, 0;
	neg.f32 	%f61, %f59;
	selp.f32 	%f62, %f59, %f61, %p11;
	add.s32 	%r85, %r94, 1;
	and.b32  	%r86, %r85, 2;
	setp.eq.s32 	%p12, %r86, 0;
	neg.f32 	%f63, %f60;
	selp.f32 	%f64, %f60, %f63, %p12;
	mul.f32 	%f65, %f2, %f64;
	mul.f32 	%f66, %f2, %f62;
	mul.f32 	%f67, %f1, %f65;
	mul.f32 	%f68, %f66, 0f00000000;
	sub.f32 	%f69, %f67, %f68;
	mul.f32 	%f70, %f65, 0f00000000;
	fma.rn.f32 	%f71, %f1, %f66, %f70;
	div.rn.f32 	%f72, %f69, %f12;
	mad.lo.s32 	%r87, %r90, %r28, %r5;
	mad.lo.s32 	%r88, %r87, %r27, %r4;
	mad.lo.s32 	%r89, %r88, %r26, %r6;
	mul.wide.s32 	%rd27, %r89, 4;
	add.s64 	%rd28, %rd3, %rd27;
	ld.global.nc.f32 	%f73, [%rd28];
	add.f32 	%f74, %f73, %f72;
	add.s64 	%rd29, %rd2, %rd27;
	st.global.f32 	[%rd29], %f74;
	div.rn.f32 	%f75, %f71, %f12;
	ld.global.nc.f32 	%f76, [%rd28+4];
	add.f32 	%f77, %f76, %f75;
	st.global.f32 	[%rd29+4], %f77;
	add.s32 	%r90, %r90, 1;
	setp.lt.s32 	%p13, %r90, %r29;
	@%p13 bra 	$L__BB0_3;

$L__BB0_12:
	ret;

}

`
)
