package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for KineticEnergy kernel
var KineticEnergy_code cu.Function

// Stores the arguments for KineticEnergy kernel invocation
type KineticEnergy_args_t struct {
	arg_energy  unsafe.Pointer
	arg_dux     unsafe.Pointer
	arg_duy     unsafe.Pointer
	arg_duz     unsafe.Pointer
	arg_rho_    unsafe.Pointer
	arg_rho_mul float32
	arg_Nx      int
	arg_Ny      int
	arg_Nz      int
	argptr      [9]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for KineticEnergy kernel invocation
var KineticEnergy_args KineticEnergy_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	KineticEnergy_args.argptr[0] = unsafe.Pointer(&KineticEnergy_args.arg_energy)
	KineticEnergy_args.argptr[1] = unsafe.Pointer(&KineticEnergy_args.arg_dux)
	KineticEnergy_args.argptr[2] = unsafe.Pointer(&KineticEnergy_args.arg_duy)
	KineticEnergy_args.argptr[3] = unsafe.Pointer(&KineticEnergy_args.arg_duz)
	KineticEnergy_args.argptr[4] = unsafe.Pointer(&KineticEnergy_args.arg_rho_)
	KineticEnergy_args.argptr[5] = unsafe.Pointer(&KineticEnergy_args.arg_rho_mul)
	KineticEnergy_args.argptr[6] = unsafe.Pointer(&KineticEnergy_args.arg_Nx)
	KineticEnergy_args.argptr[7] = unsafe.Pointer(&KineticEnergy_args.arg_Ny)
	KineticEnergy_args.argptr[8] = unsafe.Pointer(&KineticEnergy_args.arg_Nz)
}

// Wrapper for KineticEnergy CUDA kernel, asynchronous.
func k_KineticEnergy_async(energy unsafe.Pointer, dux unsafe.Pointer, duy unsafe.Pointer, duz unsafe.Pointer, rho_ unsafe.Pointer, rho_mul float32, Nx int, Ny int, Nz int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("KineticEnergy")
	}

	KineticEnergy_args.Lock()
	defer KineticEnergy_args.Unlock()

	if KineticEnergy_code == 0 {
		KineticEnergy_code = fatbinLoad(KineticEnergy_map, "KineticEnergy")
	}

	KineticEnergy_args.arg_energy = energy
	KineticEnergy_args.arg_dux = dux
	KineticEnergy_args.arg_duy = duy
	KineticEnergy_args.arg_duz = duz
	KineticEnergy_args.arg_rho_ = rho_
	KineticEnergy_args.arg_rho_mul = rho_mul
	KineticEnergy_args.arg_Nx = Nx
	KineticEnergy_args.arg_Ny = Ny
	KineticEnergy_args.arg_Nz = Nz

	args := KineticEnergy_args.argptr[:]
	cu.LaunchKernel(KineticEnergy_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("KineticEnergy")
	}
}

// maps compute capability on PTX code for KineticEnergy kernel.
var KineticEnergy_map = map[int]string{0: "",
	50: KineticEnergy_ptx_50,
	52: KineticEnergy_ptx_52,
	53: KineticEnergy_ptx_53,
	60: KineticEnergy_ptx_60,
	61: KineticEnergy_ptx_61,
	62: KineticEnergy_ptx_62,
	70: KineticEnergy_ptx_70,
	72: KineticEnergy_ptx_72,
	75: KineticEnergy_ptx_75,
	80: KineticEnergy_ptx_80}

// KineticEnergy PTX code for various compute capabilities.
const (
	KineticEnergy_ptx_50 = `
.version 8.5
.target sm_50
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_52 = `
.version 8.5
.target sm_52
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_53 = `
.version 8.5
.target sm_53
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_60 = `
.version 8.5
.target sm_60
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_62 = `
.version 8.5
.target sm_62
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_70 = `
.version 8.5
.target sm_70
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_72 = `
.version 8.5
.target sm_72
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_75 = `
.version 8.5
.target sm_75
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
	KineticEnergy_ptx_80 = `
.version 8.5
.target sm_80
.address_size 64

	// .globl	KineticEnergy

.visible .entry KineticEnergy(
	.param .u64 KineticEnergy_param_0,
	.param .u64 KineticEnergy_param_1,
	.param .u64 KineticEnergy_param_2,
	.param .u64 KineticEnergy_param_3,
	.param .u64 KineticEnergy_param_4,
	.param .f32 KineticEnergy_param_5,
	.param .u32 KineticEnergy_param_6,
	.param .u32 KineticEnergy_param_7,
	.param .u32 KineticEnergy_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd1, [KineticEnergy_param_0];
	ld.param.u64 	%rd2, [KineticEnergy_param_1];
	ld.param.u64 	%rd3, [KineticEnergy_param_2];
	ld.param.u64 	%rd4, [KineticEnergy_param_3];
	ld.param.u64 	%rd5, [KineticEnergy_param_4];
	ld.param.f32 	%f12, [KineticEnergy_param_5];
	ld.param.u32 	%r5, [KineticEnergy_param_6];
	ld.param.u32 	%r6, [KineticEnergy_param_7];
	ld.param.u32 	%r7, [KineticEnergy_param_8];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_4;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64 	%p6, %rd5, 0;
	@%p6 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.s32 	%rd7, %r4, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f4, [%rd8];
	mul.f32 	%f12, %f4, %f12;

$L__BB0_3:
	cvt.f64.f32 	%fd1, %f12;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	cvta.to.global.u64 	%rd9, %rd2;
	mul.wide.s32 	%rd10, %r4, 4;
	add.s64 	%rd11, %rd9, %rd10;
	ld.global.nc.f32 	%f5, [%rd11];
	cvta.to.global.u64 	%rd12, %rd3;
	add.s64 	%rd13, %rd12, %rd10;
	ld.global.nc.f32 	%f6, [%rd13];
	mul.f32 	%f7, %f6, %f6;
	fma.rn.f32 	%f8, %f5, %f5, %f7;
	cvta.to.global.u64 	%rd14, %rd4;
	add.s64 	%rd15, %rd14, %rd10;
	ld.global.nc.f32 	%f9, [%rd15];
	fma.rn.f32 	%f10, %f9, %f9, %f8;
	cvt.f64.f32 	%fd3, %f10;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64 	%f11, %fd4;
	cvta.to.global.u64 	%rd16, %rd1;
	add.s64 	%rd17, %rd16, %rd10;
	st.global.f32 	[%rd17], %f11;

$L__BB0_4:
	ret;

}

`
)
