package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for remainderGovaluate1X3 kernel
var remainderGovaluate1X3_code cu.Function

// Stores the arguments for remainderGovaluate1X3 kernel invocation
type remainderGovaluate1X3_args_t struct {
	arg_output unsafe.Pointer
	arg_input2 float32
	arg_input  unsafe.Pointer
	arg_N      int
	argptr     [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for remainderGovaluate1X3 kernel invocation
var remainderGovaluate1X3_args remainderGovaluate1X3_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	remainderGovaluate1X3_args.argptr[0] = unsafe.Pointer(&remainderGovaluate1X3_args.arg_output)
	remainderGovaluate1X3_args.argptr[1] = unsafe.Pointer(&remainderGovaluate1X3_args.arg_input2)
	remainderGovaluate1X3_args.argptr[2] = unsafe.Pointer(&remainderGovaluate1X3_args.arg_input)
	remainderGovaluate1X3_args.argptr[3] = unsafe.Pointer(&remainderGovaluate1X3_args.arg_N)
}

// Wrapper for remainderGovaluate1X3 CUDA kernel, asynchronous.
func k_remainderGovaluate1X3_async(output unsafe.Pointer, input2 float32, input unsafe.Pointer, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("remainderGovaluate1X3")
	}

	remainderGovaluate1X3_args.Lock()
	defer remainderGovaluate1X3_args.Unlock()

	if remainderGovaluate1X3_code == 0 {
		remainderGovaluate1X3_code = fatbinLoad(remainderGovaluate1X3_map, "remainderGovaluate1X3")
	}

	remainderGovaluate1X3_args.arg_output = output
	remainderGovaluate1X3_args.arg_input2 = input2
	remainderGovaluate1X3_args.arg_input = input
	remainderGovaluate1X3_args.arg_N = N

	args := remainderGovaluate1X3_args.argptr[:]
	cu.LaunchKernel(remainderGovaluate1X3_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("remainderGovaluate1X3")
	}
}

// maps compute capability on PTX code for remainderGovaluate1X3 kernel.
var remainderGovaluate1X3_map = map[int]string{0: "",
	50: remainderGovaluate1X3_ptx_50,
	52: remainderGovaluate1X3_ptx_52,
	53: remainderGovaluate1X3_ptx_53,
	60: remainderGovaluate1X3_ptx_60,
	61: remainderGovaluate1X3_ptx_61,
	62: remainderGovaluate1X3_ptx_62,
	70: remainderGovaluate1X3_ptx_70,
	72: remainderGovaluate1X3_ptx_72,
	75: remainderGovaluate1X3_ptx_75,
	80: remainderGovaluate1X3_ptx_80}

// remainderGovaluate1X3 PTX code for various compute capabilities.
const (
	remainderGovaluate1X3_ptx_50 = `
.version 8.5
.target sm_50
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_52 = `
.version 8.5
.target sm_52
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_53 = `
.version 8.5
.target sm_53
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_60 = `
.version 8.5
.target sm_60
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_62 = `
.version 8.5
.target sm_62
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_70 = `
.version 8.5
.target sm_70
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_72 = `
.version 8.5
.target sm_72
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_75 = `
.version 8.5
.target sm_75
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
	remainderGovaluate1X3_ptx_80 = `
.version 8.5
.target sm_80
.address_size 64

	// .globl	remainderGovaluate1X3

.visible .entry remainderGovaluate1X3(
	.param .u64 remainderGovaluate1X3_param_0,
	.param .f32 remainderGovaluate1X3_param_1,
	.param .u64 remainderGovaluate1X3_param_2,
	.param .u32 remainderGovaluate1X3_param_3
)
{
	.reg .pred 	%p<24>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [remainderGovaluate1X3_param_0];
	ld.param.f32 	%f24, [remainderGovaluate1X3_param_1];
	ld.param.u64 	%rd3, [remainderGovaluate1X3_param_2];
	ld.param.u32 	%r18, [remainderGovaluate1X3_param_3];
	mov.u32 	%r19, %ctaid.y;
	mov.u32 	%r20, %nctaid.x;
	mov.u32 	%r21, %ctaid.x;
	mad.lo.s32 	%r22, %r19, %r20, %r21;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %tid.x;
	mad.lo.s32 	%r1, %r22, %r23, %r24;
	setp.ge.s32 	%p1, %r1, %r18;
	@%p1 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd4, %rd3;
	cvt.s64.s32 	%rd1, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd4, %rd5;
	ld.global.nc.f32 	%f25, [%rd6];
	abs.f32 	%f1, %f25;
	abs.f32 	%f52, %f24;
	setp.lt.f32 	%p2, %f52, %f1;
	mov.u32 	%r51, 0;
	@%p2 bra 	$L__BB0_13;

	mul.f32 	%f3, %f1, 0f4B000000;
	setp.gtu.f32 	%p3, %f52, %f3;
	@%p3 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_3;

$L__BB0_9:
	mov.b32 	%r4, %f52;
	mov.b32 	%r5, %f3;
	and.b32  	%r29, %r4, 8388607;
	or.b32  	%r46, %r29, 1065353216;
	mov.b32 	%f49, %r46;
	add.s32 	%r30, %r5, -192937984;
	and.b32  	%r31, %r30, -8388608;
	sub.s32 	%r32, %r4, %r31;
	and.b32  	%r7, %r32, -8388608;
	setp.eq.s32 	%p9, %r7, 0;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r49;
	@%p9 bra 	$L__BB0_12;

	and.b32  	%r34, %r5, 8388607;
	or.b32  	%r35, %r34, 1065353216;
	mov.b32 	%f34, %r35;
	rcp.approx.ftz.f32 	%f13, %f34;
	neg.f32 	%f14, %f34;
	mov.u32 	%r49, 0;
	mov.u32 	%r50, %r7;

$L__BB0_11:
	min.u32 	%r36, %r50, 192937984;
	add.s32 	%r37, %r36, %r46;
	mov.b32 	%f35, %r37;
	mov.f32 	%f36, 0f80000000;
	fma.rn.f32 	%f37, %f35, %f13, %f36;
	fma.rn.f32 	%f38, %f14, %f37, %f35;
	fma.rn.f32 	%f39, %f38, %f13, %f37;
	fma.rn.f32 	%f40, %f14, %f39, %f35;
	fma.rz.f32 	%f41, %f40, %f13, %f39;
	cvt.rzi.f32.f32 	%f42, %f41;
	fma.rn.f32 	%f49, %f14, %f42, %f35;
	sub.s32 	%r50, %r50, %r36;
	mov.b32 	%r46, %f49;
	shr.u32 	%r38, %r36, 23;
	shl.b32 	%r39, %r49, %r38;
	cvt.rzi.u32.f32 	%r40, %f42;
	add.s32 	%r49, %r39, %r40;
	setp.ne.s32 	%p10, %r50, 0;
	setp.ne.s32 	%p11, %r46, 0;
	and.pred  	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_11;

$L__BB0_12:
	setp.lt.u32 	%p13, %r50, 33554432;
	shr.u32 	%r41, %r50, 23;
	selp.b32 	%r42, %r41, 3, %p13;
	shl.b32 	%r51, %r49, %r42;
	setp.gt.u32 	%p14, %r4, 2139095039;
	setp.leu.f32 	%p15, %f1, 0f00000000;
	or.pred  	%p16, %p15, %p14;
	and.b32  	%r43, %r5, -8388608;
	mov.b32 	%f43, %r43;
	selp.f32 	%f44, 0f7FFFFFFF, %f43, %p16;
	mul.f32 	%f45, %f49, 0f34000000;
	mul.f32 	%f52, %f44, %f45;
	bra.uni 	$L__BB0_13;

$L__BB0_3:
	div.approx.f32 	%f26, %f52, %f1;
	cvt.rzi.f32.f32 	%f48, %f26;
	neg.f32 	%f5, %f1;
	fma.rn.f32 	%f6, %f5, %f48, %f52;
	mov.b32 	%r2, %f6;
	mov.b32 	%r26, %f1;
	setp.lt.u32 	%p4, %r2, %r26;
	@%p4 bra 	$L__BB0_8;

	setp.gt.u32 	%p5, %r2, -2147483648;
	@%p5 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_5;

$L__BB0_7:
	add.f32 	%f32, %f48, 0fBF800000;
	add.f32 	%f33, %f32, 0fBF800000;
	setp.lt.f32 	%p8, %f6, %f5;
	selp.f32 	%f48, %f33, %f32, %p8;
	bra.uni 	$L__BB0_8;

$L__BB0_5:
	add.f32 	%f48, %f48, 0f3F800000;
	add.f32 	%f27, %f1, %f1;
	setp.ltu.f32 	%p6, %f6, %f27;
	@%p6 bra 	$L__BB0_8;

	add.f32 	%f28, %f48, 0f3F800000;
	mov.f32 	%f29, 0fC0400000;
	fma.rn.f32 	%f30, %f29, %f1, %f6;
	setp.ge.f32 	%p7, %f30, 0f00000000;
	add.f32 	%f31, %f28, 0f3F800000;
	selp.f32 	%f48, %f31, %f28, %p7;

$L__BB0_8:
	cvt.rzi.u32.f32 	%r51, %f48;
	fma.rn.f32 	%f52, %f5, %f48, %f52;

$L__BB0_13:
	add.f32 	%f19, %f52, %f52;
	setp.gt.f32 	%p17, %f19, %f1;
	@%p17 bra 	$L__BB0_15;

	setp.neu.f32 	%p18, %f19, %f1;
	and.b32  	%r44, %r51, 1;
	setp.eq.b32 	%p19, %r44, 1;
	not.pred 	%p20, %p19;
	or.pred  	%p21, %p20, %p18;
	@%p21 bra 	$L__BB0_16;

$L__BB0_15:
	sub.f32 	%f52, %f52, %f1;

$L__BB0_16:
	mov.b32 	%r45, %f24;
	setp.gt.s32 	%p22, %r45, -1;
	@%p22 bra 	$L__BB0_18;

	abs.f32 	%f46, %f52;
	setp.le.f32 	%p23, %f46, 0f7F800000;
	neg.f32 	%f47, %f52;
	selp.f32 	%f52, %f47, %f52, %p23;

$L__BB0_18:
	cvta.to.global.u64 	%rd7, %rd2;
	shl.b64 	%rd8, %rd1, 2;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f52;

$L__BB0_19:
	ret;

}

`
)
