package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for reverseX kernel
var reverseX_code cu.Function

// Stores the arguments for reverseX kernel invocation
type reverseX_args_t struct {
	arg_data_out unsafe.Pointer
	arg_data_in  unsafe.Pointer
	arg_Nx       int
	arg_Ny       int
	arg_Nz       int
	arg_oddNx    int
	argptr       [6]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for reverseX kernel invocation
var reverseX_args reverseX_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	reverseX_args.argptr[0] = unsafe.Pointer(&reverseX_args.arg_data_out)
	reverseX_args.argptr[1] = unsafe.Pointer(&reverseX_args.arg_data_in)
	reverseX_args.argptr[2] = unsafe.Pointer(&reverseX_args.arg_Nx)
	reverseX_args.argptr[3] = unsafe.Pointer(&reverseX_args.arg_Ny)
	reverseX_args.argptr[4] = unsafe.Pointer(&reverseX_args.arg_Nz)
	reverseX_args.argptr[5] = unsafe.Pointer(&reverseX_args.arg_oddNx)
}

// Wrapper for reverseX CUDA kernel, asynchronous.
func k_reverseX_async(data_out unsafe.Pointer, data_in unsafe.Pointer, Nx int, Ny int, Nz int, oddNx int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("reverseX")
	}

	reverseX_args.Lock()
	defer reverseX_args.Unlock()

	if reverseX_code == 0 {
		reverseX_code = fatbinLoad(reverseX_map, "reverseX")
	}

	reverseX_args.arg_data_out = data_out
	reverseX_args.arg_data_in = data_in
	reverseX_args.arg_Nx = Nx
	reverseX_args.arg_Ny = Ny
	reverseX_args.arg_Nz = Nz
	reverseX_args.arg_oddNx = oddNx

	args := reverseX_args.argptr[:]
	cu.LaunchKernel(reverseX_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("reverseX")
	}
}

// maps compute capability on PTX code for reverseX kernel.
var reverseX_map = map[int]string{0: "",
	50: reverseX_ptx_50,
	52: reverseX_ptx_52,
	53: reverseX_ptx_53,
	60: reverseX_ptx_60,
	61: reverseX_ptx_61,
	62: reverseX_ptx_62,
	70: reverseX_ptx_70,
	72: reverseX_ptx_72,
	75: reverseX_ptx_75,
	80: reverseX_ptx_80}

// reverseX PTX code for various compute capabilities.
const (
	reverseX_ptx_50 = `
.version 8.2
.target sm_50
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_52 = `
.version 8.2
.target sm_52
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_53 = `
.version 8.2
.target sm_53
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_60 = `
.version 8.2
.target sm_60
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_61 = `
.version 8.2
.target sm_61
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_62 = `
.version 8.2
.target sm_62
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_70 = `
.version 8.2
.target sm_70
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_72 = `
.version 8.2
.target sm_72
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_75 = `
.version 8.2
.target sm_75
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
	reverseX_ptx_80 = `
.version 8.2
.target sm_80
.address_size 64

	// .globl	reverseX

.visible .entry reverseX(
	.param .u64 reverseX_param_0,
	.param .u64 reverseX_param_1,
	.param .u32 reverseX_param_2,
	.param .u32 reverseX_param_3,
	.param .u32 reverseX_param_4,
	.param .u32 reverseX_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<32>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [reverseX_param_0];
	ld.param.u64 	%rd4, [reverseX_param_1];
	ld.param.u32 	%r5, [reverseX_param_3];
	ld.param.u32 	%r7, [reverseX_param_4];
	ld.param.u32 	%r6, [reverseX_param_5];
	ld.param.u32 	%r4, [reverseX_param_2];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r15, %r14, %r16;
	setp.eq.s32 	%p1, %r6, 1;
	selp.u32 	%r17, 1, 0, %p1;
	shr.u32 	%r18, %r4, 31;
	add.s32 	%r19, %r4, %r18;
	shr.s32 	%r20, %r19, 1;
	add.s32 	%r21, %r20, %r17;
	setp.ge.s32 	%p2, %r1, %r21;
	setp.ge.s32 	%p3, %r2, %r5;
	or.pred  	%p4, %p3, %p2;
	setp.ge.s32 	%p5, %r3, %r7;
	or.pred  	%p6, %p5, %p4;
	@%p6 bra 	$L__BB0_4;

	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd4;
	sub.s32 	%r22, %r4, %r1;
	shl.b32 	%r23, %r22, 1;
	mad.lo.s32 	%r24, %r3, %r5, %r2;
	mul.lo.s32 	%r25, %r4, %r24;
	shl.b32 	%r26, %r25, 1;
	add.s32 	%r27, %r23, %r26;
	selp.b32 	%r28, %r4, -1, %p1;
	shl.b32 	%r29, %r1, 1;
	add.s32 	%r30, %r26, %r29;
	add.s32 	%r31, %r27, -2;
	mul.wide.s32 	%rd7, %r30, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	ld.global.nc.f32 	%f2, [%rd8+4];
	mul.wide.s32 	%rd9, %r31, 4;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.nc.f32 	%f3, [%rd10];
	ld.global.nc.f32 	%f4, [%rd10+4];
	setp.eq.s32 	%p8, %r29, %r28;
	add.s64 	%rd1, %rd5, %rd7;
	add.s64 	%rd2, %rd5, %rd9;
	@%p8 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	st.global.f32 	[%rd1], %f1;
	st.global.f32 	[%rd1+4], %f2;
	st.global.f32 	[%rd2], %f3;
	st.global.f32 	[%rd2+4], %f4;
	bra.uni 	$L__BB0_4;

$L__BB0_2:
	st.global.f32 	[%rd1], %f3;
	st.global.f32 	[%rd1+4], %f4;
	st.global.f32 	[%rd2], %f1;
	st.global.f32 	[%rd2+4], %f2;

$L__BB0_4:
	ret;

}

`
)
